### ISSUE TITLE
Freeze a Model before Serving it

### ISSUE THREAD

**Issue by liuyan20062010** [bshao001/TF-Model-Deploy-Tutorial#1]
用这一块的代码生成的pb,应该是还没有固化参数吧，对吗

**Comment by liuyan20062010** [comment]
是不是应该用 tensorflow/python/tools/freeze_graph.py 固化一下参数呢

**Comment by bshao001** [comment]
@liuyan20062010 
参照这小节流程所生成的PB文件已经固化了模型的参数，不需要再运行其他程序做类似的操作。重要的是您在转化前需要找到原模型的输入和输出节点，最好给它们都命名，这样在预测是就可以按照教程中的过程调用您转化好的PB模型了。
